language: scala
sudo: false
scala:
  - 2.9.3

before_script:
  # This will download and run the Devfactory Dependency Analyser
  - git clone https://github.com/DevFactory/tpls-travis-plugin.git
  - python tpls-travis-plugin/tpls-travis-plugin.py


